public class RandomJavaCode {
    public static void main(String[] args) {
        System.out.println("This is a random piece of Java code generated by an AI.");
        int x = (int) (Math.random() * 10);
        if (x % 2 == 0) {
            System.out.println("The number is even.");
        } else {
            System.out.println("The number is odd.");
        }
    }
}
